### ISSUE TITLE
BASINML cellpose issue in python version 3.7 as mentioned in environment.yml file

### ISSUE THREAD

**Issue by bichar4** [bicbioeng/BASIN#4]
Getting error when trying to use cellpose on python3.7 from the conda basin environment:
```
>>> from cellpose import io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/basin/lib/python3.7/site-packages/cellpose/__init__.py", line 1, in <module>
    from cellpose.version import version, version_str
  File "/opt/conda/envs/basin/lib/python3.7/site-packages/cellpose/version.py", line 1, in <module>
    from importlib.metadata import PackageNotFoundError, version
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by bichar4** [comment]
Following the issue on https://stackoverflow.com/questions/73165636/no-module-named-importlib-metadata , python3.7 is no longer supported. Installing via pyhon3.8 sorted the issue.
